<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace HiGrpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>HiGrpc.Trace</code>
 */
class Trace extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string trace_no = 1;</code>
     */
    private $trace_no = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $trace_no
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string trace_no = 1;</code>
     * @return string
     */
    public function getTraceNo()
    {
        return $this->trace_no;
    }

    /**
     * Generated from protobuf field <code>string trace_no = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTraceNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_no = $var;

        return $this;
    }

}

