<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a0c636f6d6d6f6e2e70726f746f1206486947727063224a0a065265" .
            "73756c74120f0a0773756363657373180120012808120c0a04636f646518" .
            "0220012809120f0a076d65737361676518032001280912100a0874726163" .
            "655f6e6f180420012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

