<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a560a0c636f6d6d6f6e2e70726f746f12046772706322380a0652657375" .
            "6c74120f0a0773756363657373180120012808120c0a04636f6465180220" .
            "012809120f0a076d657373616765180320012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

