version: "3.7"

services:
  hi-grpc:
    image: hyperf/hyperf:8.1-alpine-v3.15-swoole
    container_name: hi-grpc
    volumes:
      - target: /opt/www
        source: hi_grpc_data
        type: volume

    working_dir: /opt/www
    ports:
      - "9501:9501"
      - "9503:9503"
      - "9505:9505"
    networks:
      - dev-network
    cpu_count: 2
    tty: true
    command:
      - /bin/sh
      - /opt/www/docker-entrypoint.sh

volumes:
  hi_grpc_data:
    name: hi_grpc_data
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind

networks:
  dev-network:
    external: true
